version: '3.1'

services:
  neoflex-service:
    build: .
    image: neoflex-service
    container_name: neoflex-service
    ports:
      - "8080:8080"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro